version: "3.3"

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - '127.0.0.1:19000:9000'
      - '127.0.0.1:19009:9009'
      - '127.0.0.1:18123:8123'
    volumes:
      - './clickhouse/init.sql:/docker-entrypoint-initdb.d/1-init.sql'